---

- name: Installing services
  yum:
    name:
      - docker
      - htop
      - tree
      - nmap
    state: present

#- name: Enable amazon=linux-extras packages
#  shell: "amazon-linux-extras install docker"

- name: Ensure docker starts
  service: name=docker state=started enabled=yes